spring.application.name=smart-workflow-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://mysql-11c5b606-ssaveetha47-d340.a.aivencloud.com:21559/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=mysecretkeymysecretkeymysecretkey123
jwt.expiration=36000000